spring.application.name=flowershopping

spring.datasource.url=jdbc:mysql://localhost:3306/flowershoppingDB?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Tokyo&characterEncoding=utf8
spring.datasource.username=root
spring.datasource.password=yaoyupeng009
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.web.flowershopping.manager.Entity
mybatis.configuration.map-underscore-to-camel-case=true

server.port=8080

url.path = https://api.tshyshopping.cn
upload.path = /home/ubuntu/upload/
image.path = /upload/
wechat.appid=wx1827dfa7462ed47b
wechat.secret=975845f160accf3bd7770055b3bdb116
wechat.MerchantId=1111138580
wechat.privateKeyPath=/home/ubuntu/certs/apiclient_key.pem
wechat.merchantSerialNumber=5EF1DEED524CA614BACB144985639C4B8EDA940A
wechat.apiV3Key=tingsanhuayu1203tingsanhuayu1203
wechat.pubKeyPath=/home/ubuntu/certs/pub_key.pem
wechat.pubKeyID=PUB_KEY_ID_0111111385802026041200211921002000

spring.rabbitmq.host=35.77.21.199
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=Yyp1311898504
spring.rabbitmq.listener.simple.acknowledge-mode=auto
spring.rabbitmq.listener.simple.prefetch=1
spring.rabbitmq.listener.simple.concurrency=1
spring.rabbitmq.listener.simple.max-concurrency=5